replicaCount: 1

image:
  repository: ghcr.io/berriai/litellm-database
  pullPolicy: Always
  tag: ""

service:
  type: ClusterIP
  port: 4000

db:
  useExisting: false
  deployStandalone: true

envVars:
  UI_USERNAME: "admin"
  UI_PASSWORD: "admin123"

masterkeySecretName: "litellm-master-key"
masterkeySecretKey: "PROXY_MASTER_KEY"

proxy_config:
  model_list:
    - model_name: qwen3-5-27b-fp8
      litellm_params:
        model: openai/qwen3-5-27b-fp8
        api_base: http://vllm-router-service.vllm.svc.cluster.local:80/v1
        api_key: "dummy"
  general_settings:
    master_key: os.environ/PROXY_MASTER_KEY

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "3Gi"